== 주문

=== 주문 생성

주문을 생성할 수 있습니다.

operation::create-order[snippets='http-request,request-headers,request-fields,http-response,response-headers']

=== 주문 취소

주문을 취소할 수 있습니다.

operation::cancel-order[snippets='http-request,request-headers,path-parameters,http-response']

=== 주문 수락

주문을 수락할 수 있습니다.

operation::accept-order[snippets='http-request,request-headers,path-parameters,request-fields,http-response']

=== 주문 목록 조회 for 가게

가게에서 주문 목록을 조회할 수 있습니다.

operation::find-order-by-restaurant[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== 주문 상세 조회 for 가게

가게의 특정 주문을 상세 조회할 수 있습니다.

operation::find-detail-order-for-restaurant[snippets='http-request,request-headers,path-parameters,http-response,response-headers,response-fields']

=== 주문 목록 조회 for 회원

회원의 주문 목록을 조회할 수 있습니다.

operation::find-order-by-customer[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']

=== 주문 상세 조회 for 회원

회원의 특정 주문을 상세 조회할 수 있습니다.

operation::find-detail-order-by-customer[snippets='http-request,request-headers,http-response,response-headers,response-fields']

=== 주문 통계 for 가게

가게의 기간별 주문 통계를 조회할 수 있습니다.

operation::find-order-statistics[snippets='http-request,request-headers,request-fields,http-response,response-headers,response-fields']
