version: 0.0
os: linux

files:
  - source: /
    destination: /product
permissions:
  - object: /product/
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
